Apptwo/urls.py
from django.urls import path
from . import views
from Apptwo import views
app_name='Apptwo'
urlpatterns=[
path('',views.index,name='index'),
path('register/',views.entry,name='form'),
path('login/',views.loginpage,name='f'),
]

Pro2/urls.py
from django.contrib import admin
from django.urls import path,include
from Apptwo import urls,views
urlpatterns = [

    path('logout/',views.log_out,name='logout'),
    path('admin/', admin.site.urls),
    path('',include('Apptwo.urls')),
    path('accounts/',include('user_profile.urls')),
    path('jobs/',include('job.urls')),
    path('profile',include('user_profile.urls'))
]

job/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name='job'
urlpatterns=[
path('',views.check,name='check'),
path('s/',views.joblist.as_view(),name='joblist'),
#path('s/<int:pk>', views.jobdetail.as_view(), name='jobdetail'),
url(r'^s/(?P<pk>\d+)/$',views.jobdetail.as_view(),name='jobdetail'),
path('trend',views.trending,name='trending')
]

user_profile/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
app_name='u'
urlpatterns = [
    path('',views.prof),
    path('password/', views.change_password, name='cp'),
    path('resume/',views.resume,name='resume')
]

Apptwo/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
# Create your models here.
class Register(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    def __str__(self):
        return self.user.first_name

job/models.py
from django.db import models

# Create your models here.
class job(models.Model):
    Designation=models.CharField(max_length=240)
    company_name=models.CharField(max_length=240)
    job_description=models.CharField(max_length=240)
    Starting_date=models.DateField()
    search_count=models.IntegerField(default=0)
    def __str__(self):
        return self.job_description

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    age=models.PositiveIntegerField()
    address=models.CharField(max_length=250)
    state=models.CharField(max_length=250)
    work_experience=models.CharField(max_length=250)
    qualification = models.CharField(max_length=100)

Apptwo/forms.py
from django import forms
from .models import User,Register
class signup(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'inputstyle'}))
    class Meta():
        model=User
        fields=('first_name','last_name','email','username','password')
        help_texts = {
            'username': None,
            'email': None,
        }
        widgets={
            'first_name':forms.TextInput(attrs={'class':'inputstyle'}),
            'last_name':forms.TextInput(attrs={'class':'inputstyle'}),
            'email':forms.EmailInput(attrs={'class':'inputstyle'}),
            'username':forms.TextInput(attrs={'class':'inputstyle'}),
        }
class regform(forms.ModelForm):
    class Meta:
        model=Register
        fields=('phone_number',)
        widgets={
            'phone_number':forms.TextInput(attrs={'class':'inputstyle'})
        }
class loginformm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={'class':'inputstyle'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'inputstyle'}))

user_profile/forms.py
from django import forms
from .models import Profile

class FormName(forms.ModelForm):


    class Meta:
        model = Profile
        fields ='__all__'

Apptwo/views.py
from django.shortcuts import render
import requests
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from .forms import signup,regform,loginformm
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('Apptwo:index'))

def index(request):
    return render(request,'main.html')
def entry(request):

    if request.method=='POST':
        user_form=signup(data=request.POST)
        profile_form=regform(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            profile=profile_form.save(commit=False)
            profile.user=user
            profile.save()
            return HttpResponseRedirect(reverse('Apptwo:f'))
        else:
            print(user_form.errors,profile_form.errors)
            print("errror")
    else:
        user_form=signup()
        profile_form=regform()

    return render(request,'App_two/registerform.html',{'user_form':user_form,
            'profile_form':profile_form})
def loginpage(request):

    if request.method=='POST':
        form=loginformm(data=request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user=authenticate(username=username,password=password)
            if(user):
                login(request,user)
                print("DONE")
                return HttpResponseRedirect(reverse('Apptwo:index'))
            else:
                print("Wornf password /username")
    else:
        form=loginformm()
    return render(request,'App_two/log.html',{'f':form})
def main(request):
    return render(request,'Apptwo/main.html')

job/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import job
# Create your views here.
class joblist(ListView):
    model=job
    paginate_by = 10
    queryset = job.objects.all()
class jobdetail(DetailView):
    context_object_name='job_detail'
    model=job
    template_name='job/jobdetail.html'
def check(request):
    if request.method=='POST':
        search=request.POST.get('Search')
        print(search)
        jobs=job.objects.order_by('company_name')
            #print(str(j.job_description))
        k= job.objects.filter(job_description__contains=search)
        for j in k:
            j.search_count=j.search_count+1
            j.save()
        return render (request,'job/search.html',{'search':k})

                #print(j)
    else:
        pass
    return render(request,'main.html')
def trending(request):
    k=job.objects.all().order_by('-search_count')[:10]
    return render(request,'job/trending.html',{'trend':k})

user_profile/views.py
# Create your views here.
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from.forms import FormName
def prof(request):
    return render(request,'user_profile/base.html')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('u:cp')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'user_profile/passreset.html', {
        'form': form,
    })
def resume(request):
    if request.method=='POST':
        form=FormName(data=request.POST)
        if form.is_valid():
            f=form.save()
            return HttpResponse("Done")
    else:
        form=FormName()
    return render(request,'user_profile/user.html',{'form':form})

templates/App_two/log.html
{%extends 'main.html'%}
<html lang="en" dir="ltr">
  <head>
    	{% load static %}

    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
{%block s%}
<link rel="stylesheet" type="text/css" href="{% static 'App_two/log.css' %}">
    <form class="container sd" method="post">


    {%csrf_token%}
    {{f.as_p}}
    <input type="submit"id="hover" value='Login'>
      </form>
      {%endblock %}
  </body>
</html>

templates/App_two/login.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'App_two/muv.css' %}">

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
	<div class ="sd "  >
		<h2 id="title">The Movie reviewer</h2>
		<img  id="logo" src="{% static "App_two/images.jpg" %}" alt="My image">
		<form id="form"  >
 <label class="font">First name</label>
 <br>
 <br>
  <input class="inputstyle"  type="text" name="firstname">
  <br>
  <br>

  <label class="font">Last name</label>
   <br>
   <br>
  <input  class="inputstyle" type="text" name="lastname"><br><br>
   <label  class="font">Email id</label><br>
   <br>
  <input class="inputstyle" type="Email"   name="email">
  <br>
  <br>
  <label class="font">Password</label>
  <br><br>
  <input class="inputstyle" type="Password" name="Password">

  <button id="hover" >Login</button>
		</form>
</div>
</body>
</html>

templates/App_two/registerform.html
{%extends 'main.html'%}
<html lang="en" dir="ltr">
<head>

  <meta charset="utf-8">
  <title></title>
</head>
  <body>
{%block s%}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'App_two/register.css' %}">
    <form class="container sd" method="post">
      {%csrf_token%}
      {{user_form.as_ul}}
      {{profile_form.as_p}}
      <input type="submit" class="mymove "id="hover">
    </form>
    {%endblock%}
  </body>
</html>

templates/job/job_list.html
{%extends 'main.html'%}
<html lang="en" dir="ltr">
  <head>
    {%load static%}
    <meta charset="utf-8">
    <title></title>

    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

{%block s%}
<body style="background-color:black;!important">

<link rel="stylesheet" href="{%static 'job/display.css'%}">

<div class="center">
  <div class="row">
    <div class="col"><h2>Company</h2>
    </div>
    <div class="col">
    <h2>Job Post</h2>
    </div>

     <div class="w-100"></div>
  {% for job in job_list %}

  <div class="col"><p style="font-family:Times New Roman;font-size:25px;">{{job.company_name}}</p></div>
  <div class="col"><a href="{{job.id}}" style="font-family:Times New Roman;font-size:20px;">{{job.job_description}}</a></div>

 <div class="w-100"></div>
 <hr style="display: block;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    margin-left: auto;
    margin-right: auto;
    border-style: inset;
    border-width: 2px;">
  {%endfor%}
</div>

    {% if is_paginated %}
  <ul class="pagination" style=" margin: auto;
    width: 50%; ">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
  </div>
</div>

{% endif %}
</div>



{%endblock%}
  </body>
</html>

templates/job/jobdetail.html
{%extends 'main.html' %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {%block s%}


<table class="table table-striped table-dark ">
  <thead >
    <tr>
      <th scope="col">#</th>
      <th scope="col">Company</th>
      <th scope="col">Job Designation </th>
      <th scope="col">Description</th>
    </tr>

    <tr>
      <th scope="row">1</th>
      <td> {{job_detail.company_name}}</td>
      <td>{{job_detail.job_description}}</td>
      <td>  {{job_detail.Designation}}</td>
    </tr>

  </tbody>
</table>



    {%endblock%}
  </body>
</html>

templates/job/search.html
{%extends 'main.html'%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
{% block s%}

<table class="table table-striped table-dark">
  <thead>
    <tr>

      <th scope="col">Company name</th>
      <th scope="col"> Designation </th>
      <th scope="col">Start Date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        {% for j in search %}

      <td>{{j.company_name}}</td>
      <td><a href="{%url 'job:jobdetail' pk=j.id %}">{{j.job_description}}</a></td>
      <td>{{j.Starting_date}}</td>
    </tr>
      {%endfor%}
  </tbody>
</table>
{%endblock%}
  </body>
</html>

templates/job/trending.html
{% extends 'main.html'%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

{%block s%}
    <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col"><h2 style="color:#0e4de0">Trending now</h2> </th>
      </tr>
    </thead>
    {% for j in trend %}
    <tbody>
    <tr>
    <td><h4 style="color:#0fe093">{{forloop.counter}}]
       {{j.job_description}}</h4></td>
      </tr>
    </tbody>

    {%endfor %}
    </table>
    {%endblock %}
  </body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		{%load static%}
	<link rel="stylesheet" href="{% static 'App_two/m.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Do+Hyeon" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<ul class="nav nav-pills nav-fill s">
			<a class="star navbar-brand " href="{%url 'Apptwo:index'%}">Your Hired</a>



		{%if user.is_authenticated%}

			<li class='nav-item'>
				<a href="{%url 'logout'%}">Logout</a> </li>
		{% else %}
		<li class="nav-item">
	    <a class="nav-link" href="{%url 'Apptwo:form'%}">Register</a>
	  </li>
		<li class="nav-item">
		 <a class="nav-link" href="{%url 'Apptwo:f'%}">Login</a>
	 </li>

	 {%endif %}
	 {%if user.is_authenticated%}
	 <li class="nav-item">
		 <li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">My profile</a>
		<div class="dropdown-menu">
			<a class="dropdown-item design" href="{% url 'u:resume' %}">Resume</a>
			<a class="dropdown-item design" href="{%url 'u:cp'%}">Change Password</a>
			<a class="dropdown-item design" href="{%url 'job:joblist'%}">Find Jobs</a>
			<div class="dropdown-divider"></div>
			<a class="dropdown-item design" href="{%url 'job:trending'%}"><strong style=" text-decoration: underline;
    text-decoration-color: red;">On Demand Jobs</strong></a>
		</div>
	</li>
	</li>
	{%endif%}
	</ul>





		{%block s%}

		<form action="{%url 'job:check'%}" method="post">
			{%csrf_token%}
			<div class="container ">
					<h1 >Welcome</h1>
								<h1>Get your desired job </h1>
			<input type="text" name="Search" placeholder="Search job">
			</div>
		</form>
					{%endblock %}



	</body>
</html>

templates/user_profile/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>User profile </h1>
  </body>
</html>

templates/user_profile/passreset.html
{% extends 'main.html' %}
{% block s%}
<form method="post">
  {% csrf_token %}
  <label><strong>Username:  </strong> </label>
  {{request.user.username}}
  <br>
  <label><strong>First name:  </strong></label>
  {{request.user.first_name}}
<br>
<label><strong>Last name:  </strong> </label>
  {{request.user.last_name}}
  {{ form.as_p }}
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
  <button type="submit">Save changes</button>
</form>
{% endblock %}

templates/user_profile/user.html
{%extends 'main.html'%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
{%block s%}
    <form  method="post">


    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" name="sub" >
    </form>
    {%endblock%}
  </body>
</html>